# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
    - name: Slim SSH Action
      # You may pin to the exact commit or the version.
      # uses: a2m1/slim-ssh-action@6d6a054b02a6a35973b16aeeba1a1d405f22cd12
      uses: a2m1/slim-ssh-action@v0.0.1
      with:
        # Host for SSH connection
        host: ec2-3-142-114-49.us-east-2.compute.amazonaws.com
        port: 22
        # Username for SSH connection
        username: ubuntu
        # Content of  the private key. Eg content of ~/.ssh/id_rsa
        key: ${{ secrets.KEY }}
        # Command to be executed on the remote host
        script: |
          killall gunicorn
          cd flasktest3/Scheduler-Experiment1/
          git pull
          source venv/bin/activate
          sudo systemctl daemon-reload
          sudo systemctl restart flasktest3
          sudo systemctl enable flasktest3
          sudo systemctl restart nginx
          sudo systemctl enable nginx
        
          
